version: '3.8'

services:
  booking2-app:
    build: .
    container_name: booking2-app-prod
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    user: "1001:1001"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: booking2-db
    environment:
      POSTGRES_DB: booking2
      POSTGRES_USER: ${DB_USER:-booking2}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: