version: '3.8'

services:
  booking2-app:
    build: .
    container_name: booking2-app-prod
    ports:
      - "3001:3001"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USER:-booking2}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_DATABASE=booking2
    restart: unless-stopped
    user: "1001:1001"
    depends_on:
      - db
    networks:
      - booking2-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: postgres:15-alpine
    container_name: booking2-db
    environment:
      POSTGRES_DB: booking2
      POSTGRES_USER: ${DB_USER:-booking2}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - booking2-network

volumes:
  postgres_data:

networks:
  booking2-network:
    driver: bridge