import { MigrationInterface, QueryRunner } from "typeorm";

export class BaseLineBD1770331567748 implements MigrationInterface {
    name = 'BaseLineBD1770331567748'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "pabellon" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(1) NOT NULL, "campus_id" uuid NOT NULL, CONSTRAINT "PK_0c3a2df063b56fdecfd6112ddc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "responsable" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "rol_usuario_id" uuid NOT NULL, "recurso_id" uuid, "clase_id" uuid, "campus_id" uuid, "curso_modalidad_id" uuid, CONSTRAINT "PK_4a49c7b18592ee4ee474538cf7c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "campus" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(50) NOT NULL, "codigo" character varying(50) NOT NULL, CONSTRAINT "UQ_91ecf325920bb7c18ce7ca040e9" UNIQUE ("codigo"), CONSTRAINT "PK_150aa1747b3517c47f9bd98ea6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "laboratorio" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(100) NOT NULL, "codigo" character varying(50) NOT NULL, "campus_id" uuid NOT NULL, CONSTRAINT "UQ_ac05d8801782cee123948990a2a" UNIQUE ("codigo"), CONSTRAINT "PK_0da9d571d9f912a3329aa4bdbda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "laboratorio_aula" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "laboratorio_id" uuid NOT NULL, "aula_id" uuid NOT NULL, CONSTRAINT "PK_99ec17975a682a5cb8aa47cb8f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "aula" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(100) NOT NULL, "codigo" character varying(50), "pabellon_id" uuid NOT NULL, CONSTRAINT "UQ_2e7307c63ef2d60f8753772c890" UNIQUE ("codigo"), CONSTRAINT "PK_f4b5d2e277c6146e2572c6ee76a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "horario" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "dia" character varying(1) NOT NULL, "inicio" character varying(20) NOT NULL, "fin" character varying(20) NOT NULL, "clase_aula_id" uuid NOT NULL, CONSTRAINT "PK_3c89ff4250bf835ce1f861313c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clase_aula" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "clase_id" uuid NOT NULL, "aula_id" uuid NOT NULL, CONSTRAINT "PK_0fe5e595c07b0fc5294afd7e414" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "estudiante" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombres" character varying(100) NOT NULL, "apellidos" character varying(100) NOT NULL, "correo" character varying(100) NOT NULL, "telefono" character varying(20) NOT NULL, "sexo" character varying(50), "direccion" character varying(50), "estado_civil" character varying(50), CONSTRAINT "PK_c7507c4641e36b102952aefc33b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "matricula_clase" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "clase_id" uuid NOT NULL, "estudiante_id" uuid NOT NULL, CONSTRAINT "PK_bc26ac8084ae49cd9a98d6fcb76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recurso_curso_modalidad_periodo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "inicio" TIMESTAMP NOT NULL, "fin" TIMESTAMP NOT NULL, "recurso_modalidad_id" uuid NOT NULL, "periodo_id" uuid NOT NULL, CONSTRAINT "PK_869dcc89e0465df2564aaa8ed6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "periodo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(7) NOT NULL, "inicio" date NOT NULL, "fin" date NOT NULL, CONSTRAINT "PK_7a8fb04e141b549da1311059257" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rol" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(100) NOT NULL, CONSTRAINT "PK_c93a22388638fac311781c7f2dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credencial" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "usuario" character varying(100), "clave" character varying(100) NOT NULL, "recurso_id" uuid NOT NULL, "rol_id" uuid NOT NULL, CONSTRAINT "PK_a693f19b3a61921040c8687fc96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "detalle_reserva" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "reserva_id" uuid NOT NULL, "credencial_id" uuid NOT NULL, CONSTRAINT "PK_a8dd64e60a1e94245750bb44bcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grupo_reserva" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "tipo" character varying NOT NULL, "recurso_id" character varying NOT NULL, "autor_id" character varying NOT NULL, "clase_id" character varying, "docente_id" character varying, "cantidad_reservas" integer NOT NULL, CONSTRAINT "PK_d2ef4cd8941fd4a53a780a48106" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reserva" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "codigo" character varying(100) NOT NULL, "mantenimiento" integer NOT NULL, "inicio" TIMESTAMP NOT NULL, "fin" TIMESTAMP NOT NULL, "cantidad_accesos" integer NOT NULL, "cantidad_credenciales" integer NOT NULL, "clase_id" uuid, "recurso_id" uuid NOT NULL, "docente_id" uuid, "autor_id" uuid NOT NULL, "grupo_reserva_id" uuid, CONSTRAINT "PK_37909c9a3ea6a72ee6f21b16129" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clase" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nrc" character varying(50) NOT NULL, "nrc_secundario" character varying(50), "inscritos" integer NOT NULL, "tipo" character varying(50) NOT NULL, "codigo_cruzado" character varying(50), "inicio" date NOT NULL, "fin" date NOT NULL, "curso_modalidad_id" uuid NOT NULL, "periodo_id" uuid NOT NULL, CONSTRAINT "UQ_24439a07656a40190970f18c609" UNIQUE ("nrc"), CONSTRAINT "PK_9a493a2bbf7d40e3738abcedc31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facultad" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(100) NOT NULL, CONSTRAINT "PK_9543579ebfaf8962147f06a1a61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "eap" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(100) NOT NULL, "facultad_id" uuid NOT NULL, CONSTRAINT "PK_92b2d4fe234bdba0e0114ad6914" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(50) NOT NULL, CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "curso" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "codigo" character varying(20) NOT NULL, "codigo_cruzado" character varying(20), "nombre" character varying(100) NOT NULL, "descripcion" character varying(100), "eap_id" uuid, "plan_id" uuid NOT NULL, CONSTRAINT "PK_76073a915621326fb85f28ecc5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "modalidad" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(50) NOT NULL, CONSTRAINT "PK_13ded8f543ee9dc2c6254b85b27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "curso_modalidad" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "curso_id" uuid NOT NULL, "modalidad_id" uuid NOT NULL, CONSTRAINT "PK_d27e27a0709e16617bb5ebaf005" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recurso_curso_modalidad" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "curso_modalidad_id" uuid NOT NULL, "recurso_id" uuid NOT NULL, CONSTRAINT "PK_f933fb145acd0b6b281afe99daa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contacto" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombres" character varying(50) NOT NULL, "apellidos" character varying(100), "telefono" character varying(20) NOT NULL, "correo" character varying(100), "proveedor_id" uuid NOT NULL, CONSTRAINT "PK_fcab8128cce0aac92da26cf1883" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proveedor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(50) NOT NULL, "pais" character varying(100) NOT NULL, "ruc" character varying(20), "telefono" character varying(20), "correo" character varying(100), "descripcion" character varying(150), CONSTRAINT "PK_405f60886417ece76cb5681550a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "seccion_email" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asunto" character varying NOT NULL, "tipo" character varying NOT NULL, "link" character varying NOT NULL, "recurso_id" uuid NOT NULL, CONSTRAINT "PK_03e0a2f75c4183d0b646ddf7aac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipo_acceso" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(50) NOT NULL, CONSTRAINT "PK_8cd41cd17dcbf9ec0d361203532" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipo_recurso" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(50) NOT NULL, CONSTRAINT "PK_f755b38129f8c8d9393d2e2986e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recurso" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombre" character varying(100) NOT NULL, "descripcion" character varying(255), "link_declaracion" character varying(255) NOT NULL, "link_guia" character varying(255), "link_aula_virtual" character varying(255), "tiempo_reserva" integer NOT NULL, "asignacion_preferencial" integer, "capacidad" integer NOT NULL, "tipo_recurso_id" uuid NOT NULL, "proveedor_id" uuid NOT NULL, "tipo_acceso_id" uuid NOT NULL, CONSTRAINT "PK_950598935447507614b0413f784" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "declaracion_jurada" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "rol_usuario_id" uuid, "recurso_id" uuid, CONSTRAINT "PK_0a2d4f4cc83af68bc63f36116fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rol_usuario" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "asignacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "usuario_id" uuid NOT NULL, "rol_id" uuid NOT NULL, CONSTRAINT "PK_9e67fdf2204d62497de7fa29079" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuario" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creacion" TIMESTAMP NOT NULL DEFAULT now(), "estado" integer NOT NULL DEFAULT '1', "nombres" character varying(100) NOT NULL, "apellidos" character varying(150) NOT NULL, "correo_institucional" character varying(100) NOT NULL, "correo_personal" character varying(100), "telefono_institucional" character varying(50), "telefono_personal" character varying(50), "sexo" character varying(50), "direccion" character varying(200), CONSTRAINT "PK_a56c58e5cabaa04fb2c98d2d7e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "pabellon" ADD CONSTRAINT "FK_2ee581c05526fbd2a67fd343243" FOREIGN KEY ("campus_id") REFERENCES "campus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "responsable" ADD CONSTRAINT "FK_eabc99c6a1793b7f6bca6898933" FOREIGN KEY ("rol_usuario_id") REFERENCES "rol_usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "responsable" ADD CONSTRAINT "FK_e86b5ba878dfe0968297c19b227" FOREIGN KEY ("recurso_id") REFERENCES "recurso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "responsable" ADD CONSTRAINT "FK_23c1a5676039cfd78433a703b3d" FOREIGN KEY ("clase_id") REFERENCES "clase"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "responsable" ADD CONSTRAINT "FK_50171c3456e1379560ddefe591c" FOREIGN KEY ("campus_id") REFERENCES "campus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "responsable" ADD CONSTRAINT "FK_f86fbf77492b2c2db1f8dc9b4bc" FOREIGN KEY ("curso_modalidad_id") REFERENCES "curso_modalidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratorio" ADD CONSTRAINT "FK_d9f966860d64b493a5a95887d5d" FOREIGN KEY ("campus_id") REFERENCES "campus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratorio_aula" ADD CONSTRAINT "FK_24efbbe392b39c58b083f517aa1" FOREIGN KEY ("laboratorio_id") REFERENCES "laboratorio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "laboratorio_aula" ADD CONSTRAINT "FK_56741afb2bc001c0b9143605304" FOREIGN KEY ("aula_id") REFERENCES "aula"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aula" ADD CONSTRAINT "FK_5b0faf0b9820e0eb68d8518ed39" FOREIGN KEY ("pabellon_id") REFERENCES "pabellon"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "horario" ADD CONSTRAINT "FK_f54d2ae79d1e99d86b1e36ea6cb" FOREIGN KEY ("clase_aula_id") REFERENCES "clase_aula"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clase_aula" ADD CONSTRAINT "FK_484a8c068d4e39e419218f2f32d" FOREIGN KEY ("clase_id") REFERENCES "clase"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clase_aula" ADD CONSTRAINT "FK_43395afeb6d832450929280dc7e" FOREIGN KEY ("aula_id") REFERENCES "aula"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matricula_clase" ADD CONSTRAINT "FK_41705e0acf43a51989530f18290" FOREIGN KEY ("clase_id") REFERENCES "clase"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matricula_clase" ADD CONSTRAINT "FK_538a75b586b063ed9007b85c389" FOREIGN KEY ("estudiante_id") REFERENCES "estudiante"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurso_curso_modalidad_periodo" ADD CONSTRAINT "FK_8a39cde080a27dca2029306d309" FOREIGN KEY ("recurso_modalidad_id") REFERENCES "recurso_curso_modalidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurso_curso_modalidad_periodo" ADD CONSTRAINT "FK_8feec32618adb92a1ad6b39e8ff" FOREIGN KEY ("periodo_id") REFERENCES "periodo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credencial" ADD CONSTRAINT "FK_7f173f66868a641331c7d6b54b4" FOREIGN KEY ("recurso_id") REFERENCES "recurso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credencial" ADD CONSTRAINT "FK_eaaa230eb0658197c4017852f30" FOREIGN KEY ("rol_id") REFERENCES "rol"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalle_reserva" ADD CONSTRAINT "FK_35fa172f7785a9e4a73e07c0515" FOREIGN KEY ("reserva_id") REFERENCES "reserva"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalle_reserva" ADD CONSTRAINT "FK_bbb3b43c407ff15ed377248a09f" FOREIGN KEY ("credencial_id") REFERENCES "credencial"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reserva" ADD CONSTRAINT "FK_bd8f2ce9ce946aacf174092d665" FOREIGN KEY ("clase_id") REFERENCES "clase"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reserva" ADD CONSTRAINT "FK_335364bcb29c7f77625373f1163" FOREIGN KEY ("recurso_id") REFERENCES "recurso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reserva" ADD CONSTRAINT "FK_9a2149632d6be922f8d793ce5c1" FOREIGN KEY ("docente_id") REFERENCES "rol_usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reserva" ADD CONSTRAINT "FK_794f5e6002d76bc50d12ba13da1" FOREIGN KEY ("autor_id") REFERENCES "rol_usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reserva" ADD CONSTRAINT "FK_7440e80587e829000422ffa1b73" FOREIGN KEY ("grupo_reserva_id") REFERENCES "grupo_reserva"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clase" ADD CONSTRAINT "FK_79f45a4d86cd55ea98a29f8ea1d" FOREIGN KEY ("curso_modalidad_id") REFERENCES "curso_modalidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clase" ADD CONSTRAINT "FK_499819672d8bee437d6ce80c2d4" FOREIGN KEY ("periodo_id") REFERENCES "periodo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "eap" ADD CONSTRAINT "FK_4d3ef29db073111588f8068b088" FOREIGN KEY ("facultad_id") REFERENCES "facultad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curso" ADD CONSTRAINT "FK_c79569e13a49e175e412f15bfdc" FOREIGN KEY ("eap_id") REFERENCES "eap"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curso" ADD CONSTRAINT "FK_f90a2379efe8b32ef052bbecf83" FOREIGN KEY ("plan_id") REFERENCES "plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curso_modalidad" ADD CONSTRAINT "FK_3bf7828b51c9757c13090f1bc6f" FOREIGN KEY ("curso_id") REFERENCES "curso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "curso_modalidad" ADD CONSTRAINT "FK_6ee097c18df63992ee4063e0b96" FOREIGN KEY ("modalidad_id") REFERENCES "modalidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurso_curso_modalidad" ADD CONSTRAINT "FK_6b25f58d0b28e77518025cb0ac9" FOREIGN KEY ("curso_modalidad_id") REFERENCES "curso_modalidad"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurso_curso_modalidad" ADD CONSTRAINT "FK_ed0b21f0301623af74797fc7339" FOREIGN KEY ("recurso_id") REFERENCES "recurso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacto" ADD CONSTRAINT "FK_33383f213b73117dea6ec610456" FOREIGN KEY ("proveedor_id") REFERENCES "proveedor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seccion_email" ADD CONSTRAINT "FK_79b872918cf2609a9024af9be8e" FOREIGN KEY ("recurso_id") REFERENCES "recurso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurso" ADD CONSTRAINT "FK_e5617f01c10a04e1b77ebb7a830" FOREIGN KEY ("tipo_recurso_id") REFERENCES "tipo_recurso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurso" ADD CONSTRAINT "FK_7610739e58101d4591edcc83b69" FOREIGN KEY ("proveedor_id") REFERENCES "proveedor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurso" ADD CONSTRAINT "FK_6e5a74a82a616ffc2d5f8f00bfd" FOREIGN KEY ("tipo_acceso_id") REFERENCES "tipo_acceso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "declaracion_jurada" ADD CONSTRAINT "FK_06b4532cbf31357ebabc2bd762d" FOREIGN KEY ("rol_usuario_id") REFERENCES "rol_usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "declaracion_jurada" ADD CONSTRAINT "FK_c6a1285ad9c177e3e1903b15c58" FOREIGN KEY ("recurso_id") REFERENCES "recurso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_usuario" ADD CONSTRAINT "FK_fdca2a999290ebb9822163d68cb" FOREIGN KEY ("usuario_id") REFERENCES "usuario"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_usuario" ADD CONSTRAINT "FK_0e5423debca58e5ee5f0fa8e850" FOREIGN KEY ("rol_id") REFERENCES "rol"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rol_usuario" DROP CONSTRAINT "FK_0e5423debca58e5ee5f0fa8e850"`);
        await queryRunner.query(`ALTER TABLE "rol_usuario" DROP CONSTRAINT "FK_fdca2a999290ebb9822163d68cb"`);
        await queryRunner.query(`ALTER TABLE "declaracion_jurada" DROP CONSTRAINT "FK_c6a1285ad9c177e3e1903b15c58"`);
        await queryRunner.query(`ALTER TABLE "declaracion_jurada" DROP CONSTRAINT "FK_06b4532cbf31357ebabc2bd762d"`);
        await queryRunner.query(`ALTER TABLE "recurso" DROP CONSTRAINT "FK_6e5a74a82a616ffc2d5f8f00bfd"`);
        await queryRunner.query(`ALTER TABLE "recurso" DROP CONSTRAINT "FK_7610739e58101d4591edcc83b69"`);
        await queryRunner.query(`ALTER TABLE "recurso" DROP CONSTRAINT "FK_e5617f01c10a04e1b77ebb7a830"`);
        await queryRunner.query(`ALTER TABLE "seccion_email" DROP CONSTRAINT "FK_79b872918cf2609a9024af9be8e"`);
        await queryRunner.query(`ALTER TABLE "contacto" DROP CONSTRAINT "FK_33383f213b73117dea6ec610456"`);
        await queryRunner.query(`ALTER TABLE "recurso_curso_modalidad" DROP CONSTRAINT "FK_ed0b21f0301623af74797fc7339"`);
        await queryRunner.query(`ALTER TABLE "recurso_curso_modalidad" DROP CONSTRAINT "FK_6b25f58d0b28e77518025cb0ac9"`);
        await queryRunner.query(`ALTER TABLE "curso_modalidad" DROP CONSTRAINT "FK_6ee097c18df63992ee4063e0b96"`);
        await queryRunner.query(`ALTER TABLE "curso_modalidad" DROP CONSTRAINT "FK_3bf7828b51c9757c13090f1bc6f"`);
        await queryRunner.query(`ALTER TABLE "curso" DROP CONSTRAINT "FK_f90a2379efe8b32ef052bbecf83"`);
        await queryRunner.query(`ALTER TABLE "curso" DROP CONSTRAINT "FK_c79569e13a49e175e412f15bfdc"`);
        await queryRunner.query(`ALTER TABLE "eap" DROP CONSTRAINT "FK_4d3ef29db073111588f8068b088"`);
        await queryRunner.query(`ALTER TABLE "clase" DROP CONSTRAINT "FK_499819672d8bee437d6ce80c2d4"`);
        await queryRunner.query(`ALTER TABLE "clase" DROP CONSTRAINT "FK_79f45a4d86cd55ea98a29f8ea1d"`);
        await queryRunner.query(`ALTER TABLE "reserva" DROP CONSTRAINT "FK_7440e80587e829000422ffa1b73"`);
        await queryRunner.query(`ALTER TABLE "reserva" DROP CONSTRAINT "FK_794f5e6002d76bc50d12ba13da1"`);
        await queryRunner.query(`ALTER TABLE "reserva" DROP CONSTRAINT "FK_9a2149632d6be922f8d793ce5c1"`);
        await queryRunner.query(`ALTER TABLE "reserva" DROP CONSTRAINT "FK_335364bcb29c7f77625373f1163"`);
        await queryRunner.query(`ALTER TABLE "reserva" DROP CONSTRAINT "FK_bd8f2ce9ce946aacf174092d665"`);
        await queryRunner.query(`ALTER TABLE "detalle_reserva" DROP CONSTRAINT "FK_bbb3b43c407ff15ed377248a09f"`);
        await queryRunner.query(`ALTER TABLE "detalle_reserva" DROP CONSTRAINT "FK_35fa172f7785a9e4a73e07c0515"`);
        await queryRunner.query(`ALTER TABLE "credencial" DROP CONSTRAINT "FK_eaaa230eb0658197c4017852f30"`);
        await queryRunner.query(`ALTER TABLE "credencial" DROP CONSTRAINT "FK_7f173f66868a641331c7d6b54b4"`);
        await queryRunner.query(`ALTER TABLE "recurso_curso_modalidad_periodo" DROP CONSTRAINT "FK_8feec32618adb92a1ad6b39e8ff"`);
        await queryRunner.query(`ALTER TABLE "recurso_curso_modalidad_periodo" DROP CONSTRAINT "FK_8a39cde080a27dca2029306d309"`);
        await queryRunner.query(`ALTER TABLE "matricula_clase" DROP CONSTRAINT "FK_538a75b586b063ed9007b85c389"`);
        await queryRunner.query(`ALTER TABLE "matricula_clase" DROP CONSTRAINT "FK_41705e0acf43a51989530f18290"`);
        await queryRunner.query(`ALTER TABLE "clase_aula" DROP CONSTRAINT "FK_43395afeb6d832450929280dc7e"`);
        await queryRunner.query(`ALTER TABLE "clase_aula" DROP CONSTRAINT "FK_484a8c068d4e39e419218f2f32d"`);
        await queryRunner.query(`ALTER TABLE "horario" DROP CONSTRAINT "FK_f54d2ae79d1e99d86b1e36ea6cb"`);
        await queryRunner.query(`ALTER TABLE "aula" DROP CONSTRAINT "FK_5b0faf0b9820e0eb68d8518ed39"`);
        await queryRunner.query(`ALTER TABLE "laboratorio_aula" DROP CONSTRAINT "FK_56741afb2bc001c0b9143605304"`);
        await queryRunner.query(`ALTER TABLE "laboratorio_aula" DROP CONSTRAINT "FK_24efbbe392b39c58b083f517aa1"`);
        await queryRunner.query(`ALTER TABLE "laboratorio" DROP CONSTRAINT "FK_d9f966860d64b493a5a95887d5d"`);
        await queryRunner.query(`ALTER TABLE "responsable" DROP CONSTRAINT "FK_f86fbf77492b2c2db1f8dc9b4bc"`);
        await queryRunner.query(`ALTER TABLE "responsable" DROP CONSTRAINT "FK_50171c3456e1379560ddefe591c"`);
        await queryRunner.query(`ALTER TABLE "responsable" DROP CONSTRAINT "FK_23c1a5676039cfd78433a703b3d"`);
        await queryRunner.query(`ALTER TABLE "responsable" DROP CONSTRAINT "FK_e86b5ba878dfe0968297c19b227"`);
        await queryRunner.query(`ALTER TABLE "responsable" DROP CONSTRAINT "FK_eabc99c6a1793b7f6bca6898933"`);
        await queryRunner.query(`ALTER TABLE "pabellon" DROP CONSTRAINT "FK_2ee581c05526fbd2a67fd343243"`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`DROP TABLE "rol_usuario"`);
        await queryRunner.query(`DROP TABLE "declaracion_jurada"`);
        await queryRunner.query(`DROP TABLE "recurso"`);
        await queryRunner.query(`DROP TABLE "tipo_recurso"`);
        await queryRunner.query(`DROP TABLE "tipo_acceso"`);
        await queryRunner.query(`DROP TABLE "seccion_email"`);
        await queryRunner.query(`DROP TABLE "proveedor"`);
        await queryRunner.query(`DROP TABLE "contacto"`);
        await queryRunner.query(`DROP TABLE "recurso_curso_modalidad"`);
        await queryRunner.query(`DROP TABLE "curso_modalidad"`);
        await queryRunner.query(`DROP TABLE "modalidad"`);
        await queryRunner.query(`DROP TABLE "curso"`);
        await queryRunner.query(`DROP TABLE "plan"`);
        await queryRunner.query(`DROP TABLE "eap"`);
        await queryRunner.query(`DROP TABLE "facultad"`);
        await queryRunner.query(`DROP TABLE "clase"`);
        await queryRunner.query(`DROP TABLE "reserva"`);
        await queryRunner.query(`DROP TABLE "grupo_reserva"`);
        await queryRunner.query(`DROP TABLE "detalle_reserva"`);
        await queryRunner.query(`DROP TABLE "credencial"`);
        await queryRunner.query(`DROP TABLE "rol"`);
        await queryRunner.query(`DROP TABLE "periodo"`);
        await queryRunner.query(`DROP TABLE "recurso_curso_modalidad_periodo"`);
        await queryRunner.query(`DROP TABLE "matricula_clase"`);
        await queryRunner.query(`DROP TABLE "estudiante"`);
        await queryRunner.query(`DROP TABLE "clase_aula"`);
        await queryRunner.query(`DROP TABLE "horario"`);
        await queryRunner.query(`DROP TABLE "aula"`);
        await queryRunner.query(`DROP TABLE "laboratorio_aula"`);
        await queryRunner.query(`DROP TABLE "laboratorio"`);
        await queryRunner.query(`DROP TABLE "campus"`);
        await queryRunner.query(`DROP TABLE "responsable"`);
        await queryRunner.query(`DROP TABLE "pabellon"`);
    }

}
